export enum QueryKeyEnum {
  CURRENT_USER = 'CURRENT_USER',
  FOCUS_QUESTION_IDS = 'FOCUS_QUESTION_IDS',
  LIST_CATEGORIES = 'LIST_CATEGORIES',
  LIST_PROCEDURE_NAMES = 'LIST_PROCEDURE_NAMES',
  LIST_QUESTIONS = 'LIST_QUESTIONS',
  LIST_TAGS = 'LIST_TAGS',
  PING = 'PING',
  QUESTION_DETAIL = 'QUESTION_DETAIL',
  QUESTION_HISTORY = 'QUESTION_HISTORY',
  QUESTION_VERSION = 'QUESTION_VERSION',
}
