export enum QueryKeyEnum {
  CURRENT_USER = 'CURRENT_USER',
  LIST_CATEGORIES = 'LIST_CATEGORIES',
  LIST_PROCEDURE_NAMES = 'LIST_PROCEDURE_NAMES',
  LIST_QUESTIONS = 'LIST_QUESTIONS',
  LIST_TAGS = 'LIST_TAGS',
  PING = 'PING',
  QUESTION_DETAIL = 'QUESTION_DETAIL',
}
